name: Python CI actions

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Xvfb 
      run: | 
        sudo apt-get update 
        sudo apt-get install -y xvfb 
    
    - name: Start Xvfb
      run: Xvfb :99 -ac -screen 0 1024x768x8 &
      env:
        DISPLAY: :99
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade wheel setuptools pip
        pip install -U -r requirements.txt
        pip install -U -r dev-requirements.txt
        
    - name: Test with pytest
      run: |
        py.test
        
    - uses: actions/upload-artifact@v2
      with:
        name: coverage-adsorcid
        path: .coverage


  coveralls:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade wheel setuptools pip
        pip install coverage==5.2.1
        pip install coveralls==2.2.0
    - uses: actions/download-artifact@master
      with:
        name: coverage-adsorcid

    - name: Coveralls
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
